font_family JetBrainsMono Nerd Font
font_size 12

bold_font auto
italic_font auto
bold_italic_font auto

cursor_shape beam
cursor_blink_interval 0.5

enable_audio_bell no

window_padding_width 0

background_opacity 1

confirm_os_window_close 0

remember_window_size yes

placement_strategy center

scrollback_lines 10000

tab_bar_edge top
tab_bar_style powerline

shell_integration enabled

include themes/tokyo-night.conf
