$bg       = rgb(1a1b26)
$bg_alt   = rgb(24283b)

$border   = rgb(414868)

$blue     = rgb(7aa2f7)
$purple   = rgb(bb9af7)
$cyan     = rgb(7dcfff)

$green    = rgb(9ece6a)
$red      = rgb(f7768e)

$text     = rgb(c0caf5)
