exec-once = awww-daemon
exec-once = swww init
exec-once = swww img ~/Pictures/wallpapers/12.png
exec-once = swaync

env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,24

source = ~/.config/hypr/current-theme.conf

# ==========================
# MONITOR
# ==========================

monitor=,preferred,auto,1

# ==========================
# PROGRAMAS
# ==========================

$terminal = kitty
$fileManager = dolphin 
$menu = wofi --show drun

# ==========================
# AUTOSTART
# ==========================

exec-once = waybar

# ==========================
# APARÊNCIA
# ==========================

general {
    gaps_in = 5
    gaps_out = 10

    border_size = 1

    col.active_border = $blue
    col.inactive_border = $border

    resize_on_border = true
    allow_tearing = false

    layout = dwindle
}

decoration {
    rounding = 0

    blur {
        enabled = true
        size = 4
        passes = 2
    }
}

animations {
    enabled = true

    animation = windows, 1, 5, default
    animation = border, 1, 10, default
    animation = fade, 1, 5, default
    animation = workspaces, 1, 5, default
}

# ==========================
# INPUT
# ==========================

input {
    kb_layout = br
    follow_mouse = 1

    touchpad {
        natural_scroll = true
    }

    sensitivity = 0
}

# ==========================
# LAYOUT
# ==========================
master {
    new_status = master
}

# ==========================
# MOD KEY
# ==========================

$mainMod = SUPER

# ==========================
# APPS
# ==========================

bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, D, exec, $menu

# ==========================
# JANELAS
# ==========================

bind = $mainMod, Q, killactive
bind = $mainMod, F, fullscreen

# ==========================
# MOVIMENTO
# ==========================

bind = $mainMod, H, movefocus, l
bind = $mainMod, J, movefocus, d
bind = $mainMod, K, movefocus, u
bind = $mainMod, L, movefocus, r

# ==========================
# MOVER JANELAS
# ==========================

bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, J, movewindow, d
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, L, movewindow, r

# ==========================
# WORKSPACES
# ==========================

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

bind = $mainMod SHIFT, E, exit 
